FROM node:22


WORKDIR /app
COPY . .
COPY app/api/src/db/migrations ./api/src/db/migrations
COPY app/api/src/db/seeds ./api/src/db/seeds
RUN npm install -g pnpm@latest
RUN pnpm install
CMD ["node", "api/src/db/migrate.mjs"]