# Use the official Node.js 18 image for development
FROM node:22

WORKDIR /app

# Install app dependencies
# Copy only the package.json and package-lock.json first for efficient caching
RUN npm install -g pnpm@9.7.0

COPY .npmrc .
COPY package.json .
COPY pnpm-lock.yaml .
RUN pnpm install
COPY . .
ARG AUTH0_DOMAIN
ARG AUTH0_CLIENT_ID
ARG AUTH0_AUDIENCE
ARG AUTH0_ISSUER

# Pass the ARG values to ENV variables so they can be accessed by the app
ENV AUTH0_DOMAIN=$AUTH0_DOMAIN
ENV AUTH0_CLIENT_ID=$AUTH0_CLIENT_ID
ENV AUTH0_AUDIENCE=$AUTH0_AUDIENCE
ENV AUTH0_ISSUER=$AUTH0_ISSUER

# Set default NODE_ENV for local development
ENV NODE_ENV=development


# Command to run the app
CMD ["pnpm", "run", "dev"]