name: Deploy revproxy

permissions:
  contents: 'read'
  packages: 'write'

on:
  push:
    branches:
      - main
    paths:
      - revproxy/**
      - .github/workflows/revproxy.yml

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITAL_OCEAN_ACCESS_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push revproxy image
        uses: docker/build-push-action@v5
        with:
          context: ./revproxy
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/slg-revproxy:latest
          file: ./revproxy/Dockerfile
          build-args: |
            CLOUDFLARE_API_KEY=${{ secrets.CLOUDFLARE_API_KEY }}

      - name: Get and store Droplet IP
        run: echo "DROPLET_IP=$(doctl compute droplet list --format PublicIPv4 --no-header www-1)" >> $GITHUB_ENV

      - name: Create SSH key file
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan ${{env.DROPLET_IP}} >> ~/.ssh/known_hosts


      - name: Deploy to DigitalOcean Droplet
        run: |
          doctl compute ssh www-1 --ssh-key-path ~/.ssh/id_rsa --ssh-user root -- << EOF
          echo "${{ secrets.PERSONAL_ACCESS_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
          docker network inspect app-default >/dev/null 2>&1 || docker network create --driver bridge app-default
          docker rm -f slg-revproxy
          docker rmi ghcr.io/${{ github.repository_owner }}/slg-revproxy:latest || true
          docker pull ghcr.io/${{ github.repository_owner }}/slg-revproxy:latest
          docker run --restart unless-stopped -d --name slg-revproxy -p 80:80 -p 443:443 --network app-default ghcr.io/${{ github.repository_owner }}/slg-revproxy:latest 
          EOF
        env:
          DIGITALOCEAN_ACCESS_TOKEN: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
          DOCKER_IMAGE_FRONTEND: ghcr.io/${{ github.repository_owner }}/slg-frontend:latest
          DOCKER_IMAGE_API: ghcr.io/${{ github.repository_owner }}/slg-api:latest
          DOCKER_IMAGE_REVPROXY: ghcr.io/${{ github.repository_owner }}/slg-revproxy:latest
        # Replace <droplet-name-or-ip>, <your-ssh-user>, and <commands> with your actual values